// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { A, AT } from './some-name-space/a.js';
export { ABC } from './some-name-space/abc.js';
export { B, BT } from './some-name-space/b.js';
export { C, CT } from './some-name-space/c.js';
