// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class B implements flatbuffers.IUnpackableObject<BT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):B {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsB(bb:flatbuffers.ByteBuffer, obj?:B):B {
  return (obj || new B()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsB(bb:flatbuffers.ByteBuffer, obj?:B):B {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new B()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

b():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startB(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addB(builder:flatbuffers.Builder, b:number) {
  builder.addFieldFloat32(0, b, 0.0);
}

static endB(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createB(builder:flatbuffers.Builder, b:number):flatbuffers.Offset {
  B.startB(builder);
  B.addB(builder, b);
  return B.endB(builder);
}

unpack(): BT {
  return new BT(
    this.b()
  );
}


unpackTo(_o: BT): void {
  _o.b = this.b();
}
}

export class BT implements flatbuffers.IGeneratedObject {
$type = "SomeNameSpace.BT" as const;
constructor(
  public b: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return B.createB(builder,
    this.b
  );
}
}
