// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class C implements flatbuffers.IUnpackableObject<CT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):C {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsC(bb:flatbuffers.ByteBuffer, obj?:C):C {
  return (obj || new C()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsC(bb:flatbuffers.ByteBuffer, obj?:C):C {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new C()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

c():string|null
c(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
c(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startC(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addC(builder:flatbuffers.Builder, cOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cOffset, 0);
}

static endC(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createC(builder:flatbuffers.Builder, cOffset:flatbuffers.Offset):flatbuffers.Offset {
  C.startC(builder);
  C.addC(builder, cOffset);
  return C.endC(builder);
}

unpack(): CT {
  return new CT(
    this.c()
  );
}


unpackTo(_o: CT): void {
  _o.c = this.c();
}
}

export class CT implements flatbuffers.IGeneratedObject {
_type = "SomeNameSpace.CT" as const;
constructor(
  public c: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const c = (this.c !== null ? builder.createString(this.c!) : 0);

  return C.createC(builder,
    c
  );
}
}
